### ISSUE TITLE
a few questions

### ISSUE THREAD

**Issue by tscholak** [hasktorch/ffi-experimental#44]
Hi, I’ve been reading through the code for the past half hour. Is everything in the `ffi` folder created by the code in `codegen`? Can I help with anything?

**Comment by junjihashimoto** [comment]
Hi,
some files (Cast.hs, Class.hs and so on) are not created by `codegen`.
It adds  the comments like `--- generated by ..` for generated files.
If you have any questions, please let me know. 

--

This repo uses `inline-c`. I should improve the c++-parser of  `inline-c`.
For now, the task has been stopping. Could you go ahead with it?
https://github.com/fpco/inline-c/pull/83

**Comment by tscholak** [comment]
yeah, I saw that you are using your own fork of inline-c which gives you what you need adhoc. I'm not sure I can be of much help with this, I'm not that fluent in c++.

**Comment by tscholak** [comment]
with regards to the code generation, I am curious of whether or not you have thought about TH for this. it's probably too late now, but maybe in the future?

**Comment by austinvhuang** [comment]
@tscholak happy to have you contribute - there's aspects that don't require C++. Can send your email to hasktorch@gmail.com and I'll send you a slack invite if you're interested.
