### ISSUE TITLE
Pin down OSX-build

### ISSUE THREAD

**Issue by junjihashimoto** [hasktorch/ffi-experimental#60]
To stabilize OSX-build on CI, we need to pin down the packages that homebrew installs.
Installation of python3 failed on OSX of circle-ci.
![image](https://user-images.githubusercontent.com/2469618/61100298-af0b8080-a4a0-11e9-8495-ef348558208e.png)

**Comment by stites** [comment]
I believe this is solved in the main repo -- either way, this issue should be reopened up in https://github.com/hasktorch/hasktorch if it is still an issue.
