### ISSUE TITLE
Archive or delete ffi-experimental?

### ISSUE THREAD

**Issue by stites** [hasktorch/ffi-experimental#72]
@junjihashimoto, @austinvhuang (cc: @apaszke)

Should we delete/archive this repository? Is everything happily living in the main hasktorch repo now?

Reasons to delete: file histories seem correct in the main repo
Reasons to archive: file histories got screw-y with my git merge and/or sentimental reasons.

**Comment by junjihashimoto** [comment]
I think both are ok. 
Before doing either, can I move the wiki of https://github.com/hasktorch/ffi-experimental/wiki
to the main hasktorch repo?

**Comment by austinvhuang** [comment]
sentimental open source :smile: ! Let's take this down the path you took w/ torch7, archive and just have a big redirect message in the README.md as the final commit.

@stites you're the grim reaper of zombie repos.

@junjihashimoto let's definitely migrate the wiki.

**Comment by stites** [comment]
:+1:

**Comment by junjihashimoto** [comment]
The migration is done.
https://github.com/hasktorch/hasktorch/wiki

**Comment by stites** [comment]
And the final git commit is added: https://github.com/hasktorch/ffi-experimental/commit/54192297742221c4d50398586ba8d187451f9ee0

Archiving now.
